import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { CalendarDays, CheckCircle2, Clock3, MapPin, Search, SlidersHorizontal, UserX } from 'lucide-react';
import Navbar from '../../components/layout/Navbar';
import { Card } from '../../components/common';
import { attendanceAPI } from '../../services/api';

const API_ORIGIN = (import.meta.env.VITE_API_BASE_URL || 'http://localhost:5000/api').replace(/\/api\/?$/, '');
const photoUrl = (photo) => photo?.startsWith('/uploads/') ? `${API_ORIGIN}${photo}` : photo;
const columnConfig = {
  Present: { title: 'Present Students', icon: CheckCircle2, border: 'border-emerald-400/30', heading: 'text-emerald-300', badge: 'bg-emerald-400/10 text-emerald-200 border-emerald-400/20', empty: 'No present students in this view.' },
  Late: { title: 'Late Students', icon: Clock3, border: 'border-amber-400/30', heading: 'text-amber-300', badge: 'bg-amber-400/10 text-amber-200 border-amber-400/20', empty: 'No late students in this view.' },
  Absent: { title: 'Absent Students', icon: UserX, border: 'border-rose-400/30', heading: 'text-rose-300', badge: 'bg-rose-400/10 text-rose-200 border-rose-400/20', empty: 'No absent students in this view.' },
};
const recordKey = (record) => `${record.userId?._id || record.userId || record.studentId || record.studentName}-${new Date(record.date).toISOString().slice(0, 10)}`;

const StudentCard = ({ record, config }) => {
  const confidence = record.status === 'Absent' || record.recognitionConfidence == null ? null : Math.round(record.recognitionConfidence * 100);
  return <article className={`rounded-xl border bg-[#0d2638]/90 p-4 shadow-[0_0_24px_rgba(34,211,238,0.04)] ${config.border}`}><div className="flex items-start gap-3"><img src={photoUrl(record.facePhoto || record.userId?.profilePhoto) || '/default-avatar.svg'} alt={`${record.studentName} profile`} className="h-16 w-16 shrink-0 rounded-full border border-cyan-300/30 bg-[#081b2a] object-cover" /><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><h3 className="truncate font-bold text-white">{record.studentName}</h3><span className={`shrink-0 rounded-full border px-2 py-1 text-[10px] font-semibold uppercase tracking-wide ${config.badge}`}>{record.status}</span></div><p className="mt-1 text-xs text-slate-400">{record.studentId || record.userId?.employeeId || 'ID unavailable'}</p><p className="mt-1 truncate text-xs text-slate-500">{record.userId?.department || 'Department unavailable'}</p></div></div><div className="mt-4 grid grid-cols-2 gap-3 border-t border-white/10 pt-3 text-xs"><div><p className="text-slate-500">Date & time</p><p className="mt-1 text-slate-200"><CalendarDays className="mr-1 inline" size={13} />{new Date(record.date).toLocaleDateString()} · {record.checkInTime || 'No check-in'}</p></div><div><p className="text-slate-500">Location</p><p className="mt-1 truncate text-slate-200">{record.locationAddress || (record.latitude != null ? 'GPS captured' : 'Not available')}</p></div></div><div className="mt-3 flex items-center justify-between text-xs">{confidence != null ? <span className="text-cyan-200">Confidence {confidence}%</span> : <span className="text-slate-500">Automatic absence</span>}{record.mapsLink ? <a href={record.mapsLink} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 text-cyan-300 hover:text-white"><MapPin size={13} /> Map</a> : <span className="text-slate-500">No location</span>}</div></article>;
};

const AttendanceColumn = ({ status, records }) => { const config = columnConfig[status]; const Icon = config.icon; return <section className="min-w-0"><div className="mb-3 flex items-center justify-between"><h2 className={`flex items-center gap-2 text-lg font-bold ${config.heading}`}><Icon size={18} /> {config.title}</h2><span className={`rounded-full border px-2 py-1 text-xs ${config.badge}`}>{records.length}</span></div><div className="space-y-3">{records.length ? records.map((record) => <StudentCard key={recordKey(record)} record={record} config={config} />) : <div className="rounded-xl border border-dashed border-white/10 bg-[#0d2638]/50 p-8 text-center text-sm text-slate-500">{config.empty}</div>}</div></section>; };

const AttendanceManagement = () => {
  const [records, setRecords] = useState([]);
  const [filters, setFilters] = useState({ search: '', date: '', department: '', location: '', status: '' });
  const [error, setError] = useState('');
  const loadAttendance = useCallback(async () => { try { const response = await attendanceAPI.getAll({ ...filters, limit: 100 }); setRecords(response.data.data || []); setError(''); } catch (requestError) { setError(requestError.response?.data?.message || 'Unable to load attendance.'); } }, [filters]);
  useEffect(() => { void loadAttendance(); const interval = window.setInterval(() => void loadAttendance(), 30000); return () => window.clearInterval(interval); }, [loadAttendance]);
  const updateFilter = (event) => setFilters((current) => ({ ...current, [event.target.name]: event.target.value }));
  const groupedRecords = useMemo(() => { const unique = new Map(); records.forEach((record) => { if (!unique.has(recordKey(record))) unique.set(recordKey(record), record); }); const values = [...unique.values()]; return { Present: values.filter((record) => record.status === 'Present'), Late: values.filter((record) => record.status === 'Late'), Absent: values.filter((record) => record.status === 'Absent') }; }, [records]);
  const summary = { present: groupedRecords.Present.length, late: groupedRecords.Late.length, absent: groupedRecords.Absent.length };
  return <div className="min-h-screen bg-[#071522] text-slate-100"><Navbar /><main className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="font-mono-label text-xs text-cyan-300">Operations / attendance history</p><h1 className="mt-2 text-3xl font-extrabold tracking-tight">Attendance History</h1><p className="mt-2 text-slate-400">Review verified attendance by status, student, and location.</p></div><div className="flex items-center gap-2 text-xs text-emerald-300"><span className="h-2 w-2 rounded-full bg-emerald-300 shadow-[0_0_12px_#6ee7b7]" /> Live updates</div></div>{error && <p className="mt-6 rounded-lg border border-rose-400/20 bg-rose-400/10 p-4 text-sm text-rose-200">{error}</p>}<div className="mt-8 grid gap-4 sm:grid-cols-3">{[['Present', summary.present, 'text-emerald-300'], ['Late', summary.late, 'text-amber-300'], ['Absent', summary.absent, 'text-rose-300']].map(([label, value, color]) => <Card key={label} className="border border-white/10 bg-[#0d2638]/90"><p className="text-sm text-slate-400">{label}</p><p className={`mt-2 text-3xl font-bold ${color}`}>{value}</p></Card>)}</div><Card className="mt-6 border border-cyan-300/10 bg-[#0d2638]/90"><div className="mb-4 flex items-center gap-2 text-sm font-semibold text-cyan-200"><SlidersHorizontal size={16} /> Search and filters</div><div className="grid gap-3 md:grid-cols-5"><div className="relative md:col-span-2"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-500" size={16} /><input name="search" value={filters.search} onChange={updateFilter} placeholder="Name, email, or ID" className="w-full rounded-lg border border-white/10 bg-[#081b2a] py-2.5 pl-9 pr-3 text-sm text-white outline-none focus:border-cyan-300" /></div><input name="date" type="date" value={filters.date} onChange={updateFilter} className="rounded-lg border border-white/10 bg-[#081b2a] px-3 py-2.5 text-sm text-white outline-none focus:border-cyan-300" /><input name="department" value={filters.department} onChange={updateFilter} placeholder="Department" className="rounded-lg border border-white/10 bg-[#081b2a] px-3 py-2.5 text-sm text-white outline-none focus:border-cyan-300" /><input name="location" value={filters.location} onChange={updateFilter} placeholder="Location" className="rounded-lg border border-white/10 bg-[#081b2a] px-3 py-2.5 text-sm text-white outline-none focus:border-cyan-300" /></div></Card><div className="mt-8 grid gap-8 lg:grid-cols-3"><AttendanceColumn status="Present" records={groupedRecords.Present} /><AttendanceColumn status="Late" records={groupedRecords.Late} /><AttendanceColumn status="Absent" records={groupedRecords.Absent} /></div></main></div>;
};

export default AttendanceManagement;