import React, { useEffect, useState } from 'react';
import { Building2, Edit3, Plus, Save, Trash2 } from 'lucide-react';
import Navbar from '../../components/layout/Navbar';
import { Button, Card, Input } from '../../components/common';
import { departmentAPI } from '../../services/api';

const DepartmentsPage = () => {
  const [departments, setDepartments] = useState([]);
  const [form, setForm] = useState({ name: '', classes: '' });
  const [editing, setEditing] = useState(null);
  const [error, setError] = useState('');
  const load = async () => { try { const response = await departmentAPI.getAll(); setDepartments(response.data.data || []); } catch (requestError) { setError(requestError.response?.data?.message || 'Unable to load departments.'); } };
  useEffect(() => { void load(); }, []);
  const save = async (event) => { event.preventDefault(); try { const payload = { name: form.name, classes: form.classes.split(',').map((item) => item.trim()).filter(Boolean) }; if (editing) await departmentAPI.update(editing, payload); else await departmentAPI.create(payload); setForm({ name: '', classes: '' }); setEditing(null); setError(''); await load(); } catch (requestError) { setError(requestError.response?.data?.message || 'Unable to save department.'); } };
  const edit = (department) => { setEditing(department._id); setForm({ name: department.name, classes: (department.classes || []).join(', ') }); };
  const deactivate = async (id) => { if (!window.confirm('Deactivate this department?')) return; await departmentAPI.deactivate(id); await load(); };
  return <div className="min-h-screen bg-[#071522] text-slate-100"><Navbar /><main className="mx-auto max-w-6xl px-4 py-8"><div className="mb-8"><p className="font-mono-label text-xs text-cyan-300">Organization / structure</p><h1 className="mt-2 text-3xl font-extrabold">Departments & Classes</h1><p className="mt-2 text-slate-400">Manage departments, classes, batches, and the structure used when assigning students.</p></div>{error && <p className="mb-5 rounded-lg bg-rose-400/10 p-3 text-sm text-rose-200">{error}</p>}<div className="grid gap-6 lg:grid-cols-[0.8fr_1.2fr]"><Card className="border border-cyan-300/15 bg-[#0d2638]/90"><h2 className="flex items-center gap-2 text-lg font-bold"><Plus size={18} /> {editing ? 'Edit department' : 'Add department'}</h2><form onSubmit={save} className="mt-5 space-y-4"><Input label="Department name" value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} required placeholder="Computer Science" /><Input label="Classes / batches" value={form.classes} onChange={(event) => setForm({ ...form, classes: event.target.value })} placeholder="Year 1, Year 2, Evening Batch" /><div className="flex gap-2"><Button type="submit"><Save size={16} /> {editing ? 'Save changes' : 'Add department'}</Button>{editing && <Button type="button" variant="ghost" onClick={() => { setEditing(null); setForm({ name: '', classes: '' }); }}>Cancel</Button>}</div></form></Card><div className="space-y-4">{departments.filter((item) => item.isActive).map((department) => <Card key={department._id} className="border border-white/10 bg-[#0d2638]/90"><div className="flex items-start justify-between gap-4"><div className="flex gap-3"><Building2 className="mt-1 text-cyan-300" size={20} /><div><h2 className="font-bold">{department.name}</h2><p className="mt-1 text-sm text-slate-400">{department.classes?.length ? department.classes.join(' · ') : 'No classes or batches assigned'}</p></div></div><div className="flex gap-2"><Button variant="ghost" size="sm" onClick={() => edit(department)} aria-label={`Edit ${department.name}`}><Edit3 size={15} /></Button><Button variant="danger" size="sm" onClick={() => { void deactivate(department._id); }} aria-label={`Deactivate ${department.name}`}><Trash2 size={15} /></Button></div></div></Card>)}{!departments.filter((item) => item.isActive).length && <Card className="border border-white/10 bg-[#0d2638]/90 text-slate-400">No departments configured yet.</Card>}</div></div></main></div>;
};
export default DepartmentsPage;
