import React, { useState } from 'react';
import { Lock, Save, Shield, SlidersHorizontal, UserCircle } from 'lucide-react';
import Navbar from '../../components/layout/Navbar';
import { Button, Card, Input } from '../../components/common';
import { authAPI } from '../../services/api';
import { useAuth } from '../../context/AuthContext';

const SettingsPage = () => {
  const { user } = useAuth();
  const [profile, setProfile] = useState({ name: user?.name || '', phone: user?.phone || '', department: user?.department || '' });
  const [rules, setRules] = useState(() => JSON.parse(localStorage.getItem('smartattend-settings') || '{"lateAfter":"09:00","closingTime":"18:00","faceThreshold":"0.60","sessionMinutes":"60"}'));
  const [message, setMessage] = useState('');
  const saveProfile = async (event) => { event.preventDefault(); await authAPI.updateProfile(profile); setMessage('Admin profile updated successfully.'); };
  const saveRules = (event) => { event.preventDefault(); localStorage.setItem('smartattend-settings', JSON.stringify(rules)); setMessage('Attendance and face-recognition settings saved for this browser.'); };
  return <div className="min-h-screen bg-[#071522] text-slate-100"><Navbar /><main className="mx-auto max-w-6xl px-4 py-8"><div className="mb-8"><p className="font-mono-label text-xs text-cyan-300">Administration / controls</p><h1 className="mt-2 text-3xl font-extrabold">Admin Settings</h1><p className="mt-2 text-slate-400">Manage administrator identity, attendance rules, recognition thresholds, and session preferences.</p></div>{message && <p className="mb-5 rounded-lg bg-emerald-400/10 p-3 text-sm text-emerald-200">{message}</p>}<div className="grid gap-6 lg:grid-cols-2"><Card className="border border-white/10 bg-[#0d2638]/90"><h2 className="flex items-center gap-2 text-lg font-bold"><UserCircle size={18} /> Admin profile</h2><form onSubmit={saveProfile} className="mt-5 space-y-4"><Input label="Name" value={profile.name} onChange={(event) => setProfile({ ...profile, name: event.target.value })} /><Input label="Phone" value={profile.phone} onChange={(event) => setProfile({ ...profile, phone: event.target.value })} /><Input label="Department" value={profile.department} onChange={(event) => setProfile({ ...profile, department: event.target.value })} /><Button type="submit"><Save size={16} /> Save profile</Button></form></Card><Card className="border border-white/10 bg-[#0d2638]/90"><h2 className="flex items-center gap-2 text-lg font-bold"><SlidersHorizontal size={18} /> Attendance rules</h2><form onSubmit={saveRules} className="mt-5 space-y-4"><Input label="Late after" type="time" value={rules.lateAfter} onChange={(event) => setRules({ ...rules, lateAfter: event.target.value })} /><Input label="Attendance closing time" type="time" value={rules.closingTime} onChange={(event) => setRules({ ...rules, closingTime: event.target.value })} /><Input label="Face match threshold" type="number" min="0" max="1" step="0.01" value={rules.faceThreshold} onChange={(event) => setRules({ ...rules, faceThreshold: event.target.value })} /><Input label="Session timeout (minutes)" type="number" min="5" value={rules.sessionMinutes} onChange={(event) => setRules({ ...rules, sessionMinutes: event.target.value })} /><Button type="submit"><Save size={16} /> Save settings</Button></form></Card><Card className="border border-white/10 bg-[#0d2638]/90 lg:col-span-2"><h2 className="flex items-center gap-2 text-lg font-bold"><Shield size={18} /> Security & session</h2><div className="mt-4 grid gap-3 text-sm text-slate-400 sm:grid-cols-3"><p className="flex items-center gap-2"><Lock size={16} className="text-cyan-300" /> Passwords are never exposed to the client.</p><p>JWT authentication protects every admin API.</p><p>Expired sessions automatically return to Login.</p></div></Card></div></main></div>;
};
export default SettingsPage;
